# Generated by Django 4.1.7 on 2023-11-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_name", models.CharField(max_length=20)),
                ("department", models.CharField(max_length=30)),
                ("salary", models.IntegerField()),
                ("DOB", models.DateField()),
                ("location", models.CharField(max_length=30)),
                ("gender", models.CharField(max_length=10)),
            ],
        ),
    ]
